### ISSUE TITLE
Windows startmenu link not created using cmdline

### ISSUE THREAD

**Issue by maphew** [newville/pyshortcuts#11]
On Win10 using `pyshortcut` command line script does not create .lnk in Startmenu (desktop link is still created though).

In 7b931517957869a3ed191053f8f72c7b42fa2779 I added a batch file to `tests` that tries to:
- determine python.exe from current env
- create a batch file to run timer.py, `timer.bat`
- use pyshortcut console script to create shortcuts to the just created timer.bat in a folder called _Shortcuts_ on desktop and in startmenu

**Comment by maphew** [comment]
still troubleshooting, but now there's an issue to hang notes on.

**Comment by newville** [comment]
@maphew  Oh, I thought I checked that this worked - but I only checked 1 Windows 10 machine.  I'll look into this too.

**Comment by newville** [comment]
@maphew  OK, it looks to me like Start Menu items should go to the `Programs` folder under the Start Menu,  so that `windows.get_startmenu()` should be

      return os.path.join(_getwinfolder(11), 'Programs')

It also looks like the GUI to make the script is wrong in using single backslashes in Windows file names instead of forward slashes.  

Does that seem correct to you?

I'll push these to master, but I'll wait to push this as version 1.6 for a few days in case more problems show up.

**Comment by maphew** [comment]
I'll spend some time on this today and see what I can do.
