### ISSUE TITLE
default shell in MacOS

### ISSUE THREAD

**Issue by lamaresh** [newville/pyshortcuts#52]
in darwin make_shortcut function the script uses by default #!/bin/bash as shell, but in lastest macOS version the default shell is zsh.
Maybe the script could get default system shell from os.getenv('SHELL')

**Comment by newville** [comment]
@lamaresh Hm, I guess "shell" could be an option. 
I'm not sure that getting it from the current shell is always the right thing to do (like, the script might really be in bash though the differences with zsh are mostly pretty small, I think), but that is probably a reasonable default.

**Comment by lamaresh** [comment]
it may be useful for environmental variable defined by users in their shell-specific config files.
if $SHELL is not specific enough even this command maybe is better: dscl . -read ~/ UserShell

**Comment by newville** [comment]
@lamaresh Hm, I think that someone writing a script for a shortcut will want some control of how that script is run, and probably not rely too heavily on user environmental variables, unless explicitly doing so.  

For my own use case (and as part of the "end of installation process" for applications), I definitely want to make a desktop app that is pointing to a known executable python script, and I want to not pay attention to what the current users PATH or any other environmental variables are.  Well, unless there are explicit environmental variables.    Anyway, I'm fine with building a bash script on macOS.  Not because bash is better but because it is good enough and is known to be available.  On macOS, zsh would also be fine.  Then again, I do not know what is gained by that -- the scripts generated for the mini-App to run are really very simple.

But, maybe I'm not fully understanding the case.

**Comment by lamaresh** [comment]
In my specific situation, my python script executes some commands with os.system and these commands are related to the $PATH variable defined in user .zsh file (I have no control on this because of external software settings).
If the shortcut is launched by a bash script (instead of zsh) $PATH won't include some directory so the os.system won't find the relative executables.
I think that generalize the script using user default shell will improve the library usability

**Comment by newville** [comment]
@lamaresh  

I may be thinking about this library differently from you. I see two typical uses cases for pyshortcuts:

  a) advanced user, probably fairly knowledgable with Python and their OS, wants to simplify running some tasks.  
  b) developer making "post-install" links to some software package, where the user is not expected to know the details of what is run, or expected to mess around with shell settings or environmental variables.  

In neither of those situations do I see that it is desirable for a script that is run by a shortcut to rely the currently defined PATH environmental variable of the user.  I would say that it would be **undesirable** to rely on a user's PATH. 

More importantly, I think that the shell running the script launched by the shortcut will necessarily source or look at the users' profile.   If I create a test app on macOS and then edit the by-default bash script in `APP/Contents/MacOS` to use `/bin/zsh` and have it do something like
   
```
   #!/bin/zsh
   printenv > $HOME/shortcut_env.txt
   ....
```

it prints out a pretty minimal PATH (`/usr/bin:/bin:/usr/sbin:/sbin`) and set of environmental variables.  It appears to not have source `.zprofile` or `.zshrc`.
